# -*- coding: utf-8 -*-
"""Internal_assessment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Pol5OFhI1iYSzSRnL1CJ8UrzBuT6HE_M
"""

#LAB1
#1.
l=int(input("\nplease enter length"))
w=int(input("\nplease enter width"))
arearect=l*w
print("area of rectangle is {}".format(arearect))

#2.
he=int(input("\nplease enter height in m"))
we=int(input("\nplease enter weight in kg"))
bmi=round(we*(100**2)/(he**2),2)
print("your bmi is {}".format(bmi))

#3.
dict={}
while 1:
  n=str(input("\nplease enter student name enter ok to stop"))
  if n.lower()=="ok":
    break
  s=int(input("\nplease enter score"))
  dict[n]=s
  print(n,s)
print(dict)

#LAB2
#4.
a=int(input("please enter your age"))
if a<18:
  print("Minor")
elif a>=18 and a<=30:
  print("adult")
else:
  print("senior")

from posixpath import split
#5.
for num in range(1,51):
  if num%2==0:
    print(num)

#6
password="akf"
while 1:
  a=str(input("Please enter correct password"))
  if a==password:
    break
print("\nBravo you entered correct one")

#7
lis=[]
k=int(input("enter num of args in list in integer"))
for i in range(k):
  t=int(input("enter values"))
  lis.append(t)
def avgfunc(lis):
  sum=0
  for i in range(len(lis)):
    sum+=lis[i]
  return sum/len(lis)
avg=avgfunc(lis)
print("average of list is {}".format(avg))

#8
s=str(input("enter a string"))
cnt=0
for i in range(len(s)):
  k=s[i]
  if k=="a":
    cnt+=1
  elif k=="e":
    cnt+=1
  elif k=="i":
    cnt+=1
  elif k=="o":
    cnt+=1
  elif k=="u":
    cnt+=1
  else:
    cnt+=0
print("number of vowels in string are {}".format(cnt))

#9
import datetime
x=datetime
print("current date and time is {}".format(x))

#10
try:
  x=int(input("enter value1 to add"))
  y=int(input("enter value2 to add"))
  k=x+y
  print(k)
except ValueError:
  print("please enter numeric inputs")

#11
try:
  i=int(input("enter a int value"))
  print("the value you entered is an integer")
except ValueError:
  print("The value you entered is not an integer")

#12
try:
  n=float(input())
  d=float(input())
except ValueError:
  print("the value entered is bad")
try:
  div=n/d
  print("the div value is",round(div,2))
except ZeroDivisionError:
  print("zero should not be entered in denominator")

#13
with open("py.txt","w") as f:
  f.write("Hello, Python!")

#14
with open("py.txt","r") as f:
  print(f.read())

#15
with open("py.txt","a") as f:
  f.write("hello")
#with open("py.txt","r") as f:
#  print(f.read())