# -*- coding: utf-8 -*-
"""LVADSUSR129-VenkataAbhishek-IA2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mqyRmoS_pvW48aRlnXP5mk-Ii1yScNfA
"""

#1
import numpy as np
rgb_image=np.array([[[255,0,0],[0,255,0],[0,0,255]],
                    [[255,255,0],[255,0,255],[0,255,255]],
                    [[127,127,127],[200,200,200],[50,50,50]]])
print(rgb_image)
rgb=rgb_image.astype('float')
gray=np.array([[[0.2989],[0.5870],[0.1140]],[[0.2989],[0.5870],[0.1140]],[[0.2989],[0.5870],[0.1140]]])
gray_scale=np.dot(rgb_image,gray)
print(gray_scale)

#2
#mean=0,std=1,
d=np.array([[150,50,20],[160,52,22],[155,51,21]])
#print(np.shape(d))
k=round(np.mean(d),2)
j=round(np.std(d),2)
print(k,j)

#3
d=np.array([[[255,0,0],[0,255,0]],
                    [[255,255,0],[255,0,255]],
                    [[127,127,127],[200,200,200]]])
#print(np.shape(d))
print(d)
k=np.series(d.flatten([0][0]),d.flatten([1][0]),d.flatten([2][0]))
t=k=np.series(d.flatten([0][1]),d.flatten([0][1]),d.flatten([0][2]))
tk=np.array([k],[t])
print(tk)

#4
d=np.array([[1,2,4],[3,4,5]])
#print(np.shape(d))
for i in range(len(d)):
  imp=abs(d[i][0]-d[i][2])
  print(imp)

#5
d=np.array([[1,2,4,5],[3,4,5,-1]])
for i in range(len(d)):
  for j in range(len(d)):
    if d[i][j+1] or d[i][j+2] or d[i][j+3]<-1:
      imp=round((d[i][j+1]+d[i][j+2])/3,2)
    imp=round((d[i][j+1]+d[i][j+2]+d[i][j+3])/3,2)
    print(imp)
    break

#6
d=np.array([[1.0,2.0,4.0],[3.0,4.0,5.0]])
a=np.array([0.1,0.2,0.3])
def func(d,a):
  return [[d[0]-a],[d[1]-a]]

k=func(d,a)
print(k)

#7
data={'name':['alice','bob','charlie','david','e','f','g'],'Age':[25,30,35,40,45,50,55],'city':['n','l','c','h','p','m','b'],'depart':['h','i','f','m','s','i','h']}
d=[]
if data['Age']<45:
  d.append(True)
else:
  d.append(False)
k=[[data['name'][d]],data['city'][d]]
print(k)

#8
d=np.array([['a','f',0.50,True],['a','f',3.00,False],['a','f',2.50,True],['a','f',1.20,True],['a','f',1.20,False],['a','b',1.20,True],['a','f',1.20,False]])
print(d)

#9
data={'name':['alice','bob','charlie','david','e','f','g'],'Age':[25,30,35,40,45,50,55],'city':['n','l','c','h','p','m','b'],'depart':['h','i','f','m','s','i','h']}
pro={'dep':['e','e','c','c','h'],'sp':['a','b','c','d','e'],'s':[70000,50000,30000,40000,60000]}
print(data)
print(pro)

#10
data={'dep':['e','e','c','c','h'],'sp':['a','b','c','d','e'],'s':[70000,50000,30000,40000,60000]}
print(data)
d=np.array(data)
print(d)
k=np.groupby(d['dep']=='e')
print(k)