# -*- coding: utf-8 -*-
"""LVADSUSR129_VenaktaAbhishek_LAB4_FA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AIs_bL554WeIkDgsBeND2B1E_JYT1kY3
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
import warnings
warnings.filterwarnings("ignore")

df_train = pd.read_csv("/content/social_network.csv")

features = ["login_activity", "posting_activity", "social_connections"]

X_train = df_train[features]

model = IsolationForest(random_state=42)
model.fit(X_train)

df_train["anomaly_score"] = model.decision_function(X_train)

df_train["Anomaly"] = ["Anomaly" if score < 0 else "Not Anomaly" for score in df_train["anomaly_score"]]

ana = df_train[df_train['Anomaly']=='Anomaly']
not_ana = df_train[df_train['Anomaly']=='Not Anomaly']

plt.figure(figsize=(10, 6))
plt.scatter(ana['social_connections'], ana['anomaly_score'], c='red', label='Anomaly')
plt.scatter(not_ana['social_connections'], not_ana['anomaly_score'], c='blue', label='Not Anomaly')
plt.xlabel("Social Connections")
plt.ylabel("Anomaly Score")
plt.legend()
plt.show()