# -*- coding: utf-8 -*-
"""LVADSUSR129_VENKATAABHISHEK_BPA_RA_Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SlvSp7LeRSoBinnwqInsH3mO2fGBC-T7
"""

import warnings
warnings.filterwarnings('ignore')
from sklearn import linear_model
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd
df=pd.read_csv('/content/Fare prediction.csv')
df.head()

df.describe()

df.info()

df.isnull().sum()
#there are no null values in the dataset so no need to fill them
#fillna to fill the null values
#df=df.fillna(method='ffill')

plt.boxplot(df['fare_amount'])

plt.boxplot(df['passenger_count'])

plt.boxplot(df['pickup_longitude'])
plt.boxplot(df['pickup_latitude'])
plt.boxplot(df['dropoff_longitude'])
plt.boxplot(df['dropoff_latitude'])

plt.xlabel('fare_amount')
plt.ylabel('passenger_count')
plt.scatter(df.fare_amount,df.passenger_count,color='r',marker='*')

X=df.drop(['fare_amount'],axis='columns')
y=df.fare_amount

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=42,test_size=0.3)
model=linear_model.LinearRegression()
model.fit(X_train,y_train)
predictions=model.predict(X_test)
print(predictions)
from sklearn.metrics import mean_squared_error,mean_absolute_error

print("MEan_squared_error")
print(mean_squared_error(predictions,y_test))
print('\n')
print("Mean absolute error")
print(mean_absolute_error(predictions,y_test))
print('\n')
print("Root Mean squared error :")
print(np.sqrt(mean_squared_error(predictions,y_test)))